name: Run Tests
on: [push]
jobs:
  test-stage:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with:
          test-results-junit: artifacts/results.xml
          code-coverage-cobertura: artifacts/coverage.xml
          test-results-pdf: artifacts/testReport.pdf
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: artifacts/results.xml
      - name: Upload code coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: artifacts/coverage.xml
      - name: Upload pdf report
        uses: actions/upload-artifact@v4
        with:
            name: pdf-Report
            path: artifacts/testReport.pdf

  simulation-stage:  
    name: Run MATLAB Simulations
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run Simulations
        uses: matlab-actions/run-command@v2
        with:
          command: |
            openProject('AstroDynamics.prj');
            cd simulations
            sunEarthMoonSimulation, sunEarthJupiterGallileanMoonsSimulation
      - name: Upload simulation artifacts
        uses: actions/upload-artifact@v4
        with:
            name: simulation-results
            overwrite: true
            path: simulations/simulationResults/